import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';

const root = path.resolve(import.meta.dirname, '..');
const sdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
const jdk = process.env.JAVA_HOME;
if (!sdk || !jdk) throw Error('Set ANDROID_HOME and JAVA_HOME to an SDK with platform 36/build-tools 36.0.0 and JDK 17+.');
const build = path.join(root, 'dist', 'tools-build');
const deps = path.join(build, 'deps');
const classes = path.join(build, 'classes');
fs.mkdirSync(deps, { recursive: true });
fs.mkdirSync(classes, { recursive: true });
const libraries = [
    ['smali-dexlib2-3.0.9.jar', 'https://dl.google.com/dl/android/maven2/com/android/tools/smali/smali-dexlib2/3.0.9/smali-dexlib2-3.0.9.jar', '8b547506f62f91d74b70f4beb4989b99e1ff61fc50b2525e9796ca35f0a351dc'],
    ['smali-util-3.0.9.jar', 'https://dl.google.com/dl/android/maven2/com/android/tools/smali/smali-util/3.0.9/smali-util-3.0.9.jar', '4673762894ba4156081fc5c642f74d6e78aef8b1a9c7702d691e3171d8cc1153'],
    ['guava-33.4.0-jre.jar', 'https://repo.maven.apache.org/maven2/com/google/guava/guava/33.4.0-jre/guava-33.4.0-jre.jar', 'b918c98a7e44dbe94ebd9fe3e40cddaadb5a93e6a78eb6008b42df237241e538']
];
for (const [name, url, checksum] of libraries) {
    const dest = path.join(deps, name);
    if (!fs.existsSync(dest)) {
        const response = await fetch(url);
        if (!response.ok) throw Error(url + ': ' + response.status);
        fs.writeFileSync(dest, Buffer.from(await response.arrayBuffer()));
    }
    const actual = crypto.createHash('sha256').update(fs.readFileSync(dest)).digest('hex');
    if (actual !== checksum) throw Error('Dependency checksum mismatch: ' + name);
    console.log(name, actual);
}
function walk(directory, suffix) {
    return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => entry.isDirectory()
        ? walk(path.join(directory, entry.name), suffix) : entry.name.endsWith(suffix) ? [path.join(directory, entry.name)] : []);
}
const bin = name => path.join(jdk, 'bin', name + (process.platform === 'win32' ? '.exe' : ''));
const android = path.join(sdk, 'platforms', 'android-36', 'android.jar');
const jars = libraries.map(([name]) => path.join(deps, name));
function run(command, args) {
    const result = spawnSync(command, args, { stdio: 'inherit' });
    if (result.status !== 0) throw Error(command + ' failed: ' + result.status);
}
run(bin('javac'), ['--release', '8', '-encoding', 'UTF-8', '-cp', [...jars, android].join(path.delimiter), '-d', classes, ...walk(path.join(root, 'patcher', 'src'), '.java')]);
const toolsDir = path.join(root, 'module', 'tools');
fs.mkdirSync(toolsDir, { recursive: true });
// Retired intermediate generated by the initial combined-helper prototype.
const retired = path.join(toolsDir, 'fcm-tools.jar');
if (fs.existsSync(retired)) fs.unlinkSync(retired);
// d8.jar is a build-tool runtime, not copied into the module.
const classFiles = walk(classes, '.class');
const catalogFiles = classFiles.filter(file => path.basename(file).startsWith('AppCatalog'));
for (const [name, files, dependencies] of [
    ['catalog.jar', catalogFiles, []],
    ['patcher.jar', classFiles.filter(file => !catalogFiles.includes(file)), jars]
]) {
    const output = path.join(toolsDir, name);
    run(bin('java'), ['-Xmx1g', '-cp', path.join(sdk, 'build-tools', '36.0.0', 'lib', 'd8.jar'), 'com.android.tools.r8.D8',
        '--min-api', '33', '--lib', android, '--output', output, ...files, ...dependencies]);
    console.log('Built', output, fs.statSync(output).size, 'bytes');
}
